services:
  db:
    image: postgres:16
    container_name: worker_reports_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: worker_reports
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - worker_reports_postgres_data:/var/lib/postgresql/data

volumes:
  worker_reports_postgres_data: