# Generated by Django 6.0.4 on 2026-06-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worknode',
            options={'ordering': ['id'], 'verbose_name': 'Работа', 'verbose_name_plural': 'Дерево работ'},
        ),
        migrations.AddField(
            model_name='worknode',
            name='source_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Ключ импорта'),
        ),
        migrations.AlterField(
            model_name='worknode',
            name='code',
            field=models.CharField(max_length=100, verbose_name='Код'),
        ),
    ]
