# Generated by Django 6.0.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_worknode_options_worknode_source_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worknode',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterModelOptions(
            name='worknode',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Работа', 'verbose_name_plural': 'Дерево работ'},
        ),
    ]
