# Generated by Django 6.0.4 on 2026-04-24 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=50, unique=True, verbose_name='Телефон')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('brigade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='masters', to='core.brigade', verbose_name='Бригада')),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
            },
        ),
    ]
