# Generated by Django 6.0.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_worknode_sort_order'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='workers',
            field=models.ManyToManyField(blank=True, related_name='masters', to='core.worker', verbose_name='Рабочие'),
        ),
    ]
