# Generated by Django 6.0.4 on 2026-04-24 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('done', 'Завершён')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('brigade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_reports', to='core.brigade', verbose_name='Бригада')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_reports', to='accounts.master', verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Дневной отчёт',
                'verbose_name_plural': 'Дневные отчёты',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportWorkerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporary_worker_name', models.CharField(blank=True, max_length=255, verbose_name='Добавленный рабочий')),
                ('status', models.CharField(choices=[('present', 'Работал'), ('absent', 'Не пришёл'), ('sick', 'Болеет'), ('vacation', 'Отпуск')], max_length=20, verbose_name='Статус')),
                ('hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Часы')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_entries', to='reports.dailyreport', verbose_name='Отчёт')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='report_entries', to='core.worker', verbose_name='Рабочий')),
            ],
            options={
                'verbose_name': 'Рабочий в отчёте',
                'verbose_name_plural': 'Рабочие в отчёте',
            },
        ),
        migrations.CreateModel(
            name='ReportWorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=255, verbose_name='Объект')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Титул')),
                ('project_section', models.CharField(blank=True, max_length=255, verbose_name='Раздел проекта')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Объём')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_items', to='reports.dailyreport', verbose_name='Отчёт')),
                ('work_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_items', to='core.worknode', verbose_name='Работа')),
            ],
            options={
                'verbose_name': 'Работа в отчёте',
                'verbose_name_plural': 'Работы в отчёте',
            },
        ),
    ]
